# <center>PIPELINE</center>

- ADH: atlas de desenvolvimento humano

# ADH

O Atlas do Desenvolvimento Humano no Brasil é um site que traz o Índice de Desenvolvimento Humano Municipal (IDHM) e outros 200 indicadores de demografia, educação, renda, trabalho, habitação e vulnerabilidade para os municípios brasileiros.

https://basedosdados.org/en/dataset/mundo-onu-adh

https://basedosdados.org/en/dataset/mundo-onu-adh/resource/2fa04257-b35c-4a6a-a0db-69ae665318ac

In [1]:
import os
import pandas as pd

In [2]:
! pip install base dos dados

Requirement already satisfied: base in /home/bruno/Documents/dev/lgdc-covid-19-and-malaria/venv-lgdc-covid-19-and-malaria/lib/python3.8/site-packages (1.0.4)
Requirement already satisfied: dos in /home/bruno/Documents/dev/lgdc-covid-19-and-malaria/venv-lgdc-covid-19-and-malaria/lib/python3.8/site-packages (1.6.0)
Requirement already satisfied: dados in /home/bruno/Documents/dev/lgdc-covid-19-and-malaria/venv-lgdc-covid-19-and-malaria/lib/python3.8/site-packages (0.1.4)
Requirement already satisfied: arrow in /home/bruno/Documents/dev/lgdc-covid-19-and-malaria/venv-lgdc-covid-19-and-malaria/lib/python3.8/site-packages (from dos) (1.1.0)
Requirement already satisfied: flask in /home/bruno/Documents/dev/lgdc-covid-19-and-malaria/venv-lgdc-covid-19-and-malaria/lib/python3.8/site-packages (from dos) (2.0.1)
Requirement already satisfied: colorlog==3.1.0 in /home/bruno/Documents/dev/lgdc-covid-19-and-malaria/venv-lgdc-covid-19-and-malaria/lib/python3.8/site-packages (from dados) (3.1.0)
Requirement already satisfied: pydash==4.3.0 in /home/bruno/Documents/dev/lgdc-covid-19-and-malaria/venv-lgdc-covid-19-and-malaria/lib/python3.8/site-packages (from dados) (4.3.0)
Requirement already satisfied: cement==2.10.2 in /home/bruno/Documents/dev/lgdc-covid-19-and-malaria/venv-lgdc-covid-19-and-malaria/lib/python3.8/site-packages (from dados) (2.10.2)
Requirement already satisfied: future==0.16.0 in /home/bruno/Documents/dev/lgdc-covid-19-and-malaria/venv-lgdc-covid-19-and-malaria/lib/python3.8/site-packages (from dados) (0.16.0)
Requirement already satisfied: python-dateutil>=2.7.0 in /home/bruno/Documents/dev/lgdc-covid-19-and-malaria/venv-lgdc-covid-19-and-malaria/lib/python3.8/site-packages (from arrow->dos) (2.8.1)
Requirement already satisfied: itsdangerous>=2.0 in /home/bruno/Documents/dev/lgdc-covid-19-and-malaria/venv-lgdc-covid-19-and-malaria/lib/python3.8/site-packages (from flask->dos) (2.0.1)
Requirement already satisfied: Werkzeug>=2.0 in /home/bruno/Documents/dev/lgdc-covid-19-and-malaria/venv-lgdc-covid-19-and-malaria/lib/python3.8/site-packages (from flask->dos) (2.0.1)
Requirement already satisfied: Jinja2>=3.0 in /home/bruno/Documents/dev/lgdc-covid-19-and-malaria/venv-lgdc-covid-19-and-malaria/lib/python3.8/site-packages (from flask->dos) (3.0.1)
Requirement already satisfied: click>=7.1.2 in /home/bruno/Documents/dev/lgdc-covid-19-and-malaria/venv-lgdc-covid-19-and-malaria/lib/python3.8/site-packages (from flask->dos) (7.1.2)
Requirement already satisfied: six>=1.5 in /home/bruno/Documents/dev/lgdc-covid-19-and-malaria/venv-lgdc-covid-19-and-malaria/lib/python3.8/site-packages (from python-dateutil>=2.7.0->arrow->dos) (1.14.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/bruno/Documents/dev/lgdc-covid-19-and-malaria/venv-lgdc-covid-19-and-malaria/lib/python3.8/site-packages (from Jinja2>=3.0->flask->dos) (2.0.1)

In [4]:
import basedosdados as bd
# Para carregar o dado direto no pandas
df = bd.read_table(dataset_id='mundo_onu_adh', 
            table_id='municipios',
            billing_project_id='lgdccovid19malaria')

Downloading: 100%|██████████| 16695/16695 [01:04<00:00, 260.52rows/s]

In [19]:
df

,id_municipio,ano,expectativa_vida,fecundidade_total,mortalidade_1,mortalidade_5,razao_dependencia,prob_sobrevivencia_40,prob_sobrevivencia_60,taxa_envelhecimento,...,pia,pia_10_14,pia_15_17,pia_18_mais,indice_escolaridade,indice_frequencia_escolar,idhm,idhm_e,idhm_l,idhm_r
0,1100015,1991,62.01,4.08,45.58,58.05,73.50,83.81,66.87,1.82,...,NaN,NaN,NaN,NaN,0.117,0.109,0.329,0.112,0.617,0.516
1,1100023,1991,66.02,3.72,32.39,41.41,69.97,88.08,74.23,1.82,...,NaN,NaN,NaN,NaN,0.200,0.199,0.432,0.199,0.684,0.593
2,1100031,1991,63.16,3.89,41.52,52.94,77.23,85.09,69.00,2.59,...,NaN,NaN,NaN,NaN,0.111,0.106,0.309,0.108,0.636,0.430
3,1100049,1991,65.03,3.81,35.37,45.19,71.11,87.08,72.44,2.47,...,NaN,NaN,NaN,NaN,0.176,0.169,0.407,0.171,0.667,0.593
4,1100056,1991,62.73,3.55,43.00,54.82,71.09,84.62,68.20,2.46,...,NaN,NaN,NaN,NaN,0.152,0.175,0.386,0.167,0.629,0.547
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16690,5222005,2010,74.10,2.10,14.40,17.04,45.11,93.03,82.02,7.17,...,10754.0,1129.0,711.0,8914.0,0.432,0.747,0.712,0.622,0.818,0.710
16691,5222054,2010,73.25,2.29,15.70,18.51,42.38,92.47,80.75,5.49,...,6192.0,622.0,380.0,5190.0,0.389,0.676,0.684,0.562,0.804,0.707
16692,5222203,2010,74.07,2.64,14.50,17.09,50.80,93.02,81.98,4.05,...,3807.0,475.0,268.0,3065.0,0.431,0.594,0.647,0.534,0.818,0.619
16693,5222302,2010,73.09,2.67,15.90,18.80,50.75,92.36,80.50,7.06,...,4298.0,508.0,314.0,3476.0,0.330,0.624,0.634,0.505,0.802,0.629
16694,5300108,2010,77.35,1.75,14.01,15.85,40.14,94.57,86.19,4.97,...,2180903.0,219091.0,130872.0,1830940.0,0.723,0.751,0.824,0.742,0.873,0.863

In [23]:
output_path = os.path.join(os.getcwd(), 'data_06')
output_file = 'data_06_brazil_indicators.csv'
df.to_csv(os.path.join(output_path, output_file))