# <center>Join dataframes df_covid and df_indicators_2</center>

1. imports
2. load datasets
3. join datafra

## 1. Imports

In [8]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm

## 2. Load datasets

In [2]:
file_covid = 'output_02_data_02_covid_cities_confirmed_cases.csv'
path_input_file_covid = os.path.join(os.getcwd(), '..', 
                                     'sprint_03_data_analysis', 'output', 
                                     file_covid)
df_covid = pd.read_csv(path_input_file_covid, delimiter=';')
del df_covid['Unnamed: 0']
df_covid['codmun'] = df_covid['codmun'].map(str).map(lambda codmun: codmun.split('.')[0])
df_covid.head()

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
0,Norte,RO,Alta Floresta D'Oeste,11,110001,11005.0,ZONA DA MATA,2020-05-02,18,22945.0,1.0,1,0,0,NaN,NaN,0.0
1,Norte,RO,Alta Floresta D'Oeste,11,110001,11005.0,ZONA DA MATA,2020-05-03,19,22945.0,1.0,0,0,0,NaN,NaN,0.0
2,Norte,RO,Alta Floresta D'Oeste,11,110001,11005.0,ZONA DA MATA,2020-05-04,19,22945.0,1.0,0,0,0,NaN,NaN,0.0
3,Norte,RO,Alta Floresta D'Oeste,11,110001,11005.0,ZONA DA MATA,2020-05-05,19,22945.0,1.0,0,0,0,NaN,NaN,0.0
4,Norte,RO,Alta Floresta D'Oeste,11,110001,11005.0,ZONA DA MATA,2020-05-06,19,22945.0,1.0,0,0,0,NaN,NaN,0.0

In [3]:
input_path_indicators_2 = os.path.join(os.getcwd(), '..', 'sprint_03_data_analysis', 'output')
input_file_indicators_2 = 'output_04_data_07_brazil_indicators_02_with_states_and_cities.csv'
df_indicators_2 = pd.read_csv(os.path.join(input_path_indicators_2, input_file_indicators_2)).drop('Unnamed: 0', axis=1)
df_indicators_2.head()

,Posição IDHM,IDHM,Posição IDHM Renda,IDHM Renda,Posição IDHM Educação,IDHM Educação,Posição IDHM Longevidade,IDHM Longevidade,Posição Mulheres,IDHM Mulheres,...,IDHM Urbano,Posição Rural,IDHM Rural,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Municipio,Estado
0,1,0.862,8,0.887,2,0.811,1,0.891,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,São Caetano do Sul,SP
1,2,0.854,5,0.890,1,0.825,11,0.849,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Águas de São Pedro,SP
2,3,0.847,22,0.873,5,0.800,4,0.870,23.0,0.871,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Florianópolis,SC
3,4,0.845,40,0.855,4,0.805,3,0.876,33.0,0.824,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Vitória,ES
4,4,0.845,1,0.894,6,0.789,9,0.854,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Balneário Camboriú,SC

## 3. Join dataframes df_covid and df_indicators_2

In [9]:
print(df_covid.shape)

li_index_covid_state_city = []

for state, city in tqdm(zip(df_covid['estado'], df_covid['municipio'])):
    index_state_city = state + '-' + city    
    li_index_covid_state_city.append(index_state_city)

arr_index_covid_state_city = np.array(li_index_covid_state_city)

df_covid.index = arr_index_covid_state_city

del li_index_covid_state_city
del arr_index_covid_state_city

(2074662, 17)

2074662it [00:01, 1255663.14it/s]

In [10]:
df_covid

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
RO-Alta Floresta D'Oeste,Norte,RO,Alta Floresta D'Oeste,11,110001,11005.0,ZONA DA MATA,2020-05-02,18,22945.0,1.0,1,0,0,NaN,NaN,0.0
RO-Alta Floresta D'Oeste,Norte,RO,Alta Floresta D'Oeste,11,110001,11005.0,ZONA DA MATA,2020-05-03,19,22945.0,1.0,0,0,0,NaN,NaN,0.0
RO-Alta Floresta D'Oeste,Norte,RO,Alta Floresta D'Oeste,11,110001,11005.0,ZONA DA MATA,2020-05-04,19,22945.0,1.0,0,0,0,NaN,NaN,0.0
RO-Alta Floresta D'Oeste,Norte,RO,Alta Floresta D'Oeste,11,110001,11005.0,ZONA DA MATA,2020-05-05,19,22945.0,1.0,0,0,0,NaN,NaN,0.0
RO-Alta Floresta D'Oeste,Norte,RO,Alta Floresta D'Oeste,11,110001,11005.0,ZONA DA MATA,2020-05-06,19,22945.0,1.0,0,0,0,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DF-Brasília,Centro-Oeste,DF,Brasília,53,530010,53001.0,DISTRITO FEDERAL,2021-05-17,20,3015268.0,393631.0,1049,8345,28,NaN,NaN,1.0
DF-Brasília,Centro-Oeste,DF,Brasília,53,530010,53001.0,DISTRITO FEDERAL,2021-05-18,20,3015268.0,394223.0,592,8366,21,NaN,NaN,1.0
DF-Brasília,Centro-Oeste,DF,Brasília,53,530010,53001.0,DISTRITO FEDERAL,2021-05-19,20,3015268.0,395213.0,990,8399,33,NaN,NaN,1.0
DF-Brasília,Centro-Oeste,DF,Brasília,53,530010,53001.0,DISTRITO FEDERAL,2021-05-20,20,3015268.0,396087.0,874,8422,23,NaN,NaN,1.0
DF-Brasília,Centro-Oeste,DF,Brasília,53,530010,53001.0,DISTRITO FEDERAL,2021-05-21,20,3015268.0,396985.0,898,8442,20,NaN,NaN,1.0

In [11]:
print(df_indicators_2.shape)

li_index_indicators_2_state_city = []

for state, city in tqdm(zip(df_indicators_2['Estado'], df_indicators_2['Municipio'])):
    index_state_city = state + '-' + city    
    li_index_indicators_2_state_city.append(index_state_city)

arr_index_indicators_2_state_city = np.array(li_index_indicators_2_state_city)

df_indicators_2.index = arr_index_indicators_2_state_city

del li_index_indicators_2_state_city
del arr_index_indicators_2_state_city

5565it [00:00, 1003107.21it/s]

(5565, 27)

In [12]:
df_indicators_2

,Posição IDHM,IDHM,Posição IDHM Renda,IDHM Renda,Posição IDHM Educação,IDHM Educação,Posição IDHM Longevidade,IDHM Longevidade,Posição Mulheres,IDHM Mulheres,...,IDHM Urbano,Posição Rural,IDHM Rural,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Municipio,Estado
SP-São Caetano do Sul,1,0.862,8,0.887,2,0.811,1,0.891,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,São Caetano do Sul,SP
SP-Águas de São Pedro,2,0.854,5,0.890,1,0.825,11,0.849,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Águas de São Pedro,SP
SC-Florianópolis,3,0.847,22,0.873,5,0.800,4,0.870,23.0,0.871,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Florianópolis,SC
ES-Vitória,4,0.845,40,0.855,4,0.805,3,0.876,33.0,0.824,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Vitória,ES
SC-Balneário Camboriú,4,0.845,1,0.894,6,0.789,9,0.854,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Balneário Camboriú,SC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RR-Uiramutã,345,0.453,129,0.766,462,0.276,385,0.439,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Uiramutã,RR
MA-Marajá do Sena,346,0.452,121,0.774,456,0.299,390,0.400,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Marajá do Sena,MA
AM-Atalaia do Norte,347,0.450,162,0.733,464,0.259,357,0.481,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Atalaia do Norte,AM
MA-Fernando Falcão,348,0.443,167,0.728,458,0.286,389,0.417,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fernando Falcão,MA
PA-Melgaço,349,0.418,119,0.776,466,0.207,377,0.454,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Melgaço,PA

In [13]:
df_covid_indicators = df_covid.join(df_indicators_2)

In [14]:
df_covid_indicators.head().iloc[1]

regiao                                   Norte
estado                                      AC
municipio                           Acrelândia
coduf                                       12
codmun                                  120001
codRegiaoSaude                         12002.0
nomeRegiaoSaude             BAIXO ACRE E PURUS
data                                2020-03-30
semanaEpi                                   14
populacaoTCU2019                       15256.0
casosAcumulado                             6.0
casosNovos                                   4
obitosAcumulado                              0
obitosNovos                                  0
Recuperadosnovos                           NaN
emAcompanhamentoNovos                      NaN
interior/metropolitana                     0.0
Posição IDHM                             221.0
IDHM                                     0.604
Posição IDHM Renda                        87.0
IDHM Renda                               0.808
Posição IDHM Educação                    311.0
IDHM Educação                            0.466
Posição IDHM Longevidade                 254.0
IDHM Longevidade                         0.584
Posição Mulheres                           NaN
IDHM Mulheres                              NaN
Posição Homens                             NaN
IDHM Homens                                NaN
Posição Negros                             NaN
IDHM Negros                                NaN
Posição Brancos                            NaN
IDHM Brancos                               NaN
Posição Urbano                             NaN
IDHM Urbano                                NaN
Posição Rural                              NaN
IDHM Rural                                 NaN
Unnamed: 21                                NaN
Unnamed: 22                                NaN
Unnamed: 23                                NaN
Unnamed: 24                                NaN
Unnamed: 25                                NaN
Municipio                           Acrelândia
Estado                                      AC
Name: AC-Acrelândia, dtype: object

In [15]:
del df_covid_indicators['Municipio']
del df_covid_indicators['Estado']

## 4. Save

In [16]:
path_output = os.path.join(os.getcwd(), 'output')
file_output = 'output_05_covid19_2020-2021_and_indicators_2010.csv'
df_covid_indicators.to_csv(os.path.join(path_output, file_output))