# <center>PIPELINE</center>

- Imports
- Load Dataframes

- Analaysis

01: nº framing per month

## Imports

In [2]:
import pandas as pd
import numpy as np
import dask
from dask import dataframe as dd
import os
from typing import Union

## Load Dataframes

In [5]:
def load_emergency_aid(blocksize: Union[str, float] = 25e6) -> dask.dataframe.core.DataFrame:
    """Return a dask dataframe

    blocksize: num bytes of each parallel dataframe chunk. egg:'25MB' or 25e6 """

    path_data_09_csvs = os.path.join(os.getcwd(), '..', 'sprint_01_data_collection', 'data_09', '*.csv')

    return dd.read_csv(path_data_09_csvs, sep=";", encoding="ISO-8859-1", blocksize=blocksize, dtype={
        'CPF RESPONSÁVEL': 'str',
        'CÓDIGO MUNICÍPIO IBGE': 'str',
        'NOME MUNICÍPIO': 'str', 
        'UF': 'str', 
        'NIS BENEFICIÁRIO': 'str', 
        'CPF BENEFICIÁRIO': 'str', 
        'NOME BENEFICIÁRIO': 'str', 
        'NIS RESPONSÁVEL': 'str', 
        'CPF RESPONSÁVEL': 'str', 
        'NOME RESPONSÁVEL': 'str', 
        'ENQUADRAMENTO': 'str', 
        'PARCELA': 'str', 
        'OBSERVAÇÃO': 'str', 
        'VALOR BENEFÍCIO': 'str'})

In [7]:
df_emergencial_aid = load_emergency_aid()

In [9]:
df_emergencial_aid.head()
# df_emergencial_aid.tail()

,MÊS DISPONIBILIZAÇÃO,UF,CÓDIGO MUNICÍPIO IBGE,NOME MUNICÍPIO,NIS BENEFICIÁRIO,CPF BENEFICIÁRIO,NOME BENEFICIÁRIO,NIS RESPONSÁVEL,CPF RESPONSÁVEL,NOME RESPONSÁVEL,ENQUADRAMENTO,PARCELA,OBSERVAÇÃO,VALOR BENEFÍCIO
0,202004,NaN,NaN,NaN,00000000000,***.832.922-**,ALICE CILENE DE OLIVEIRA DIAS,-2,NaN,Não se aplica,EXTRACAD,1ª,Não há,"600,00"
1,202004,NaN,NaN,NaN,00000000000,***.208.119-**,APARICIO LINHARES LOUZADA,-2,NaN,Não se aplica,EXTRACAD,1ª,Não há,"600,00"
2,202004,NaN,NaN,NaN,00000000000,***.884.918-**,CELIA APARECIDA DE SOUZA,-2,NaN,Não se aplica,EXTRACAD,1ª,Não há,"600,00"
3,202004,NaN,NaN,NaN,00000000000,***.899.219-**,CERES MARLIZE WAVRITA,-2,NaN,Não se aplica,EXTRACAD,1ª,Não há,"600,00"
4,202004,NaN,NaN,NaN,00000000000,***.904.623-**,CLEODON BORGES DA SILVA,-2,NaN,Não se aplica,EXTRACAD,1ª,Não há,"600,00"